export const generateAgreement = ({
  lender,
  borrower,
  item,
  deposit,
  startDate,
  endDate,
}) => {
  return `
TRUSTLOOP DIGITAL AGREEMENT

--------------------------------

Lender:
${lender}

Borrower:
${borrower}

Item:
${item}

Security Deposit:
₹${deposit}

Borrowing Period:
${startDate}
to
${endDate}

Terms:

1. Borrower agrees to return item in original condition.

2. Security deposit may be partially or fully deducted in case of damage.

3. AI condition reports serve as supporting evidence.

4. Both parties accept TrustLoop dispute resolution process.

Digitally Generated By TrustLoop.
`;
};